# Generated by Django 4.0.3 on 2022-03-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0002_alter_book_serie_alter_book_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverocr',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='books.book'),
        ),
    ]
