# Generated by Django 4.0.3 on 2022-03-31 15:19

from django.db import migrations, models

NUMBERS = []


def get_number(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.all():
        if book.number != None and book.number != "":
            NUMBERS.append({"id": book.pk, "nr": book.number})


def fill_number(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    for num in NUMBERS:
        pk = num["id"]
        nr = num["nr"]
        book = Book.objects.get(pk=pk)
        book.number = int(nr)
        book.save()


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0004_book_number'),
    ]

    operations = [
        migrations.RunPython(get_number, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('number', 'title', 'isbn')},
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(fill_number, reverse_code=migrations.RunPython.noop),
    ]
