# Generated by Django 4.0.3 on 2022-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0005_alter_book_options_alter_book_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
