# Generated by Django 4.0.3 on 2022-04-03 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0011_alter_book_publisher_alter_book_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='display_name',
        ),
    ]
