# Generated by Django 4.0.3 on 2022-04-16 17:59

from django.db import migrations, models

from books.models import get_combined_book_title


def fill_combined_title(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.all():
        try:
            book.combined_title = get_combined_book_title(book)
            book.save()
            print(book, "OK")
        except Exception as e:
            print(book, f"{e}")


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0013_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='combined_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(fill_combined_title, reverse_code=migrations.RunPython.noop),
    ]
