# Generated by Django 4.0.4 on 2022-04-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0014_book_combined_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('combined_title', 'isbn')},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='isbn_prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CoverOCR',
        ),
        migrations.DeleteModel(
            name='IsbnPrefix',
        ),
    ]
