# Generated by Django 4.0.4 on 2022-04-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0015_alter_book_options_alter_publisher_isbn_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='isbn_prefix',
        ),
        migrations.CreateModel(
            name='IsbnPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                related_name='prefixes', to='books.publisher')),
            ],
        ),
    ]
