# Generated by Django 4.0.4 on 2022-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0016_remove_publisher_isbn_prefix_isbnprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='isbnprefix',
            name='prefix_stripped',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
