# Generated by Django 4.0.4 on 2022-04-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_isbnprefix_prefix_stripped'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sub_categories',
            field=models.ManyToManyField(related_name='books', to='books.subcategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='books.subcategory'),
        ),
    ]
