# Generated by Django 4.0.4 on 2022-04-27 17:02

from django.db import migrations


def make_many_categories(apps, schema_editor):
    """
        Adds the Author object in Book.author to the
        many-to-many relationship in Book.authors
    """
    Book = apps.get_model('books', 'Book')

    for book in Book.objects.all():
        book.genres.add(book.sub_category)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_sub_categories_alter_book_sub_category'),
    ]

    operations = [
        migrations.RunPython(make_many_categories),
    ]
