# Generated by Django 4.0.4 on 2022-04-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20220427_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sub_category',
        ),
    ]
