# Generated by Django 4.0.4 on 2022-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_remove_book_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'subcategories'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
