# Generated by Django 4.0.4 on 2022-04-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='sub_categories',
            new_name='genre',
        ),
    ]
