# Generated by Django 4.0.4 on 2022-04-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_rename_subcategory_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
