# Generated by Django 4.0.4 on 2022-04-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_rename_genre_book_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name_plural': 'genres'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='sources',
        ),
        migrations.DeleteModel(
            name='InfoSource',
        ),
    ]
