# Generated by Django 4.0.4 on 2022-05-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_alter_genre_options_remove_book_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_collection',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.genre'),
        ),
    ]
