# Generated by Django 4.0.4 on 2022-05-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_rename_serie_series_rename_serie_book_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='combined_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
