# Generated by Django 4.0.4 on 2022-05-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_alter_book_combined_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_collection',
        ),
    ]
