# Generated by Django 4.0.4 on 2022-05-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_remove_book_in_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
