# Generated by Django 4.0.4 on 2022-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_alter_wish_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
