# Generated by Django 4.0.4 on 2022-05-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to='books.series'),
        ),
    ]
