# Generated by Django 4.0.4 on 2022-05-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_videoseries_rename_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to='books.videoseries'),
        ),
    ]
