# Generated by Django 4.0.4 on 2022-05-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_alter_video_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['series', 'season', 'episode', 'title']},
        ),
        migrations.AlterField(
            model_name='video',
            name='kind',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('CABARET', 'Cabaret'), ('IMDB100', 'IMDB Top 100'), ('MUSIC', 'Music Video'), ('SERIES', 'Series'), ('STARTREK', 'StarTrek')], max_length=20),
        ),
    ]
