# Generated by Django 4.0.4 on 2022-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_alter_video_options_remove_video_episode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='quality',
        ),
        migrations.AddField(
            model_name='video',
            name='hd',
            field=models.BooleanField(default=False),
        ),
    ]
