# Generated by Django 4.0.4 on 2022-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_remove_video_quality_video_hd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['type', 'series', 'title']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='kind',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='hd',
        ),
        migrations.RemoveField(
            model_name='video',
            name='season',
        ),
        migrations.AddField(
            model_name='video',
            name='seasons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='series',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='VideoSeries',
        ),
    ]
