# Generated by Django 4.0.4 on 2022-06-22 18:04

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0041_video_screen_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': [django.db.models.functions.text.Upper('series'), django.db.models.functions.text.Upper('title'), 'seasons']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='cover_image',
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('CABARET', 'Cabaret'), ('MUSIC', 'Music Video'), ('SERIES', 'Series'), ('STARTREK', 'StarTrek')], max_length=20),
        ),
    ]
