# Generated by Django 4.0.4 on 2022-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0042_alter_video_options_rename_cover_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('HARD_COVER', 'Hard cover'), ('SOFT_COVER', 'Soft cover')], default='UNKNOWN', max_length=20),
        ),
    ]
